# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Graft < Formula
  desc "A command line tool for merging and validating family tree JSON files."
  homepage "https://github.com/0xbs/graft"
  version "1.1.0"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/0xbs/graft/releases/download/v1.1.0/graft_1.1.0_darwin_amd64.tar.gz"
      sha256 "f000c399f6b6cc6410a083bd7bdd7ed9bdac980f2ba6d262d03f1958545b543c"

      define_method(:install) do
        bin.install "graft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/0xbs/graft/releases/download/v1.1.0/graft_1.1.0_darwin_arm64.tar.gz"
      sha256 "a55f58b0ce76de513aeddea5d179c99487f508ec85c21ad8c543bfabba02b75d"

      define_method(:install) do
        bin.install "graft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/0xbs/graft/releases/download/v1.1.0/graft_1.1.0_linux_amd64.tar.gz"
      sha256 "6b83857081dc45d37ca052761b5bfd395447c0fb5c5db666a59a20a57ad031c6"
      define_method(:install) do
        bin.install "graft"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/0xbs/graft/releases/download/v1.1.0/graft_1.1.0_linux_arm64.tar.gz"
      sha256 "5c9b6b2390d263bd435bb9d698e0d9676c331dd623d150ed48552103bb699498"
      define_method(:install) do
        bin.install "graft"
      end
    end
  end
end
