# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Secrets < Formula
  desc "A command line tool for symmetric encryption and decryption of files."
  homepage "https://github.com/0xbs/secrets"
  version "1.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/0xbs/secrets/releases/download/v1.0.6/secrets_1.0.6_darwin_amd64.tar.gz"
      sha256 "cce4fbbb3a35e99e6916c2501963b78a3c260cf3dbf6663b048d9c6d3ea58285"

      def install
        bin.install "secrets"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/0xbs/secrets/releases/download/v1.0.6/secrets_1.0.6_darwin_arm64.tar.gz"
      sha256 "b83a12273631cfe142f7db71445ca509d31004ecb8893c71a878a9d0a12686f1"

      def install
        bin.install "secrets"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/0xbs/secrets/releases/download/v1.0.6/secrets_1.0.6_linux_arm64.tar.gz"
      sha256 "2e49005e7fbf534bae738929e0ff63d8e177cd179f8e6b45c87d7e02cc165e26"

      def install
        bin.install "secrets"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/0xbs/secrets/releases/download/v1.0.6/secrets_1.0.6_linux_amd64.tar.gz"
      sha256 "df6ad1c500a5e88f56b2c2612f7fc3cfced04b1de019c429b24ebf70fa6eba7a"

      def install
        bin.install "secrets"
      end
    end
  end
end
