# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Secrets < Formula
  desc "A command line tool for symmetric encryption and decryption of files."
  homepage "https://github.com/0xbs/secrets"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/0xbs/secrets/releases/download/v1.0.3/secrets_1.0.3_darwin_amd64.tar.gz"
      sha256 "c19c83abad63a4670030c12f466f63b950cbd5bb81fb555568c821b83e44141b"

      def install
        bin.install "secrets"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/0xbs/secrets/releases/download/v1.0.3/secrets_1.0.3_darwin_arm64.tar.gz"
      sha256 "89cc7d47c6d78252e4d97b4fb0174435fe96264a2b3295746427e60a8642f92e"

      def install
        bin.install "secrets"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/0xbs/secrets/releases/download/v1.0.3/secrets_1.0.3_linux_arm64.tar.gz"
      sha256 "12179a9e5b8fd6e76cddb777cc2706e96dcd81f49b2286e5133c679c7a1aeb4d"

      def install
        bin.install "secrets"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/0xbs/secrets/releases/download/v1.0.3/secrets_1.0.3_linux_amd64.tar.gz"
      sha256 "3d2283fc26ebc16186a0ee953cc06dffd04060b77934ad0b9bf567dab5813ae5"

      def install
        bin.install "secrets"
      end
    end
  end
end
