# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Secrets < Formula
  desc "A command line tool for symmetric encryption and decryption of files."
  homepage "https://github.com/0xbs/secrets"
  version "1.0.7"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/0xbs/secrets/releases/download/v1.0.7/secrets_1.0.7_darwin_amd64.tar.gz"
      sha256 "fa88afa3952db3007708fb38ae325e1a741a48de8bc0a6eba72169d8a2db5e69"

      def install
        bin.install "secrets"
      end
    end
    on_arm do
      url "https://github.com/0xbs/secrets/releases/download/v1.0.7/secrets_1.0.7_darwin_arm64.tar.gz"
      sha256 "7df5c9ac5fd615d56e9e1f4518cd38c722d3ca97b7ceae67539f11050b264edc"

      def install
        bin.install "secrets"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/0xbs/secrets/releases/download/v1.0.7/secrets_1.0.7_linux_amd64.tar.gz"
        sha256 "01095eeb3a5405bc0122fa832a3ef466e607277f33c213728ff657a79c4cf4eb"

        def install
          bin.install "secrets"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/0xbs/secrets/releases/download/v1.0.7/secrets_1.0.7_linux_arm64.tar.gz"
        sha256 "22222d01347456505f94dc779240eff7a837bd82b79fd394a88ce7800541db7f"

        def install
          bin.install "secrets"
        end
      end
    end
  end
end
