# This file was generated by GoReleaser. DO NOT EDIT.
cask "graft" do
  name "graft"
  desc "A command line tool for merging family tree JSON files."
  homepage "https://github.com/0xbs/graft"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "graft"

  on_macos do
    on_intel do
      url "https://github.com/0xbs/graft/releases/download/v#{version}/graft_#{version}_darwin_amd64.tar.gz"
      sha256 "6fb86c15799d5a28ce139cd54be4eee265b8b63288b2b5e57e158a87c7ef1b02"
    end
    on_arm do
      url "https://github.com/0xbs/graft/releases/download/v#{version}/graft_#{version}_darwin_arm64.tar.gz"
      sha256 "0b3c3386a3ef60ddc3e49c8de33d601dc0120c2c07e222a27a7aa7b88a7c9812"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/0xbs/graft/releases/download/v#{version}/graft_#{version}_linux_amd64.tar.gz"
      sha256 "5b7d4cb796e8b7ee7352146a0964a1b785efcd7359669e692c5cc83c43423cd9"
    end
    on_arm do
      url "https://github.com/0xbs/graft/releases/download/v#{version}/graft_#{version}_linux_arm64.tar.gz"
      sha256 "7769f014b33950cee8e773d15bcd21e496e1da2296908454f3e01152e5f3a0b1"
    end
  end

  # No zap stanza required
end
