# This file was generated by GoReleaser. DO NOT EDIT.
cask "secrets" do
  name "secrets"
  desc "A command line tool for symmetric encryption and decryption of files."
  homepage "https://github.com/0xbs/secrets"
  version "1.0.12"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "secrets"

  on_macos do
    on_intel do
      url "https://github.com/0xbs/secrets/releases/download/v#{version}/secrets_#{version}_darwin_amd64.tar.gz"
      sha256 "34e8786d6c975ced02de72ef5451517e4dc101abb3dee5a277c0ee25b033a6a2"
    end
    on_arm do
      url "https://github.com/0xbs/secrets/releases/download/v#{version}/secrets_#{version}_darwin_arm64.tar.gz"
      sha256 "ba84050712a47a6fc7801c3428e59df5edbe70b58957a44417022b191c89ceb4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/0xbs/secrets/releases/download/v#{version}/secrets_#{version}_linux_amd64.tar.gz"
      sha256 "293f4522ef1191d3e9daf7be2a3a1744d4b6de828ea4285fdba8fdb49902f374"
    end
    on_arm do
      url "https://github.com/0xbs/secrets/releases/download/v#{version}/secrets_#{version}_linux_arm64.tar.gz"
      sha256 "9685b95309a0292e0c11a4387fa0ec34b9f3b434ea714267d305ad29990718a1"
    end
  end

  # No zap stanza required
end
